### ISSUE TITLE
bzminer kept crashing upon starting

### ISSUE THREAD

**Issue by setsunakaeru** [bzminer/bzminer#111] opened 2022-10-06 13:05 UTC
Some of my Rigs can run bzminer but some others seems not running and kept crashed...

![bzminer-crashes](https://user-images.githubusercontent.com/115161280/194320178-bf9e94d1-d9cc-46a6-8476-6d5d3e5c1fe5.png)

pls help

**Comment by bzminer** [comment] 2022-10-06 22:23
Hi @setsunakaeru , which windows version are you running? Which Nvidia driver? Can you try to run with --disable_opencl?

**Comment by setsunakaeru** [comment] 2022-10-07 03:24
Thanks @bzminer it works, may i know why this command line need to be included?
Appreciate if you can share some info.

**Comment by bzminer** [comment] 2022-10-07 05:28
Hey @setsunakaeru , it's a bug that's fixed in the betas (or hopefully fixed). The problem is that opencl, which is used for amd, sometimes crashes when it tries to enumerate some devices. I believe it's an amd driver install issue, or possibly an issue with the opencl drivers for Nvidia. We don't need to enumerate Nvidia devices with opencl though so I've disabled that by default in the betas. Hoping to push a new release tomorrow so this won't be a problem going forward

**Comment by setsunakaeru** [comment] 2022-10-07 05:36
Noted with thanks, appreciate for the prompt reply.

**Closed** 2022-10-20 15:13 UTC
